---
title: "DataViz_practice"
author: "Sophie Wulfing"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, dev="cairo_pdf")
#knitr::write_bib look into

library(tidyr)
library(plyr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(ggpubr)
library(knitr)
library(kableExtra)


setwd("C:/Users/swulfing/Documents/GitHub/TanakekeProject/URUVS")

URUV_data <- read.csv("Datasheets/MasterRecordingData_clean.csv")

ID_data <- read.csv('Datasheets/URUV/speciesguide.csv')
Bahasa_data <- read.csv('Datasheets/URUV/speciesBahasa.csv') %>%
  select(Name_Data, Name_Local, Ditangkap) %>%
  rename(dataCode = Name_Data)

ID_data <- merge(x = ID_data, y = Bahasa_data, by = 'dataCode')

URUV_data$MONTH <- factor(URUV_data$MONTH, levels = c("JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"))
URUV_data$SITE_TYPE <- factor(URUV_data$SITE_TYPE, levels = c("D", "E", "L"))
URUV_data$DESA <- factor(URUV_data$DESA)

ID_data$REPEAT <- NA

for(i in 1:nrow(ID_data)){
  if(ID_data$NameChanged[i] %in% ID_data$dataCode){
    
    ID_data$REPEAT[i] <- 1
    
  }
  
}

ID_data <- ID_data %>%
  filter(is.na(REPEAT))

```


```{r AllSpecies, results = 'asis', echo = FALSE, fig.show = "hold", out.width = "50%"}

ggplot(URUV_data, aes(x=DESA, y=NO_ALLSPECIES)) + 
  geom_boxplot() 
  #geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(URUV_data, aes(x=SITE_TYPE, y=NO_ALLSPECIES)) + 
  geom_boxplot() 
  #geom_jitter(shape=16, position=position_jitter(0.2))

```

```{r FishSpecies, results = 'asis', echo = FALSE, fig.show = "hold", out.width = "50%"}

ggplot(URUV_data, aes(x=DESA, y=NO_FISHSPECIES)) + 
  geom_boxplot() 
  #geom_jitter(shape=16, position=position_jitter(0.1))

ggplot(URUV_data, aes(x=SITE_TYPE, y=NO_FISHSPECIES)) + 
  geom_boxplot() 
  #geom_jitter(shape=16, position=position_jitter(0.1))

```

```{r ShannonsDiversity}

# MAKE LIST OF SPECIES NOT TO INCLUDE UNIDGUPPY, 

# DOUBLE CHECK THIS CALCULATION. based off this https://sqlpad.io/tutorial/shannon-diversity-calculate/

# # Sample data: species counts
# species_counts <- c(10, 20, 30, 40)
# 
# # Calculate proportions
# species_proportions <- species_counts / sum(species_counts)
# 
# # Calculate Shannon Diversity Index
# shannon_diversity <- -sum(species_proportions * log(species_proportions))
# print(shannon_diversity)


shannon <- URUV_data %>%
      group_by(SITE_TYPE) %>%
      summarise(SHANNON_AVG = mean(SHANNON_DIV))

desa <- URUV_data %>%
      group_by(DESA) %>%
      summarise(SHANNON_AVG = mean(SHANNON_DIV))

ggplot(data=shannon, aes(x=SITE_TYPE, y=SHANNON_AVG, fill = SITE_TYPE)) +
      geom_bar(stat="identity", color = "black") +
      xlab("Jenis Mangrove") +
      ylab("Index") +
      #geom_text(aes(label=SHANNON_AVG), vjust=-0.3, size=3.5) +
      theme_minimal() +
      scale_fill_manual(values = c("#b41515", "#ffff00", "#0474c4"),
                    labels = c("Dihancur","EMR", "Alami")) +
      theme(legend.title=element_blank())

# ggplot(data=desa, aes(x=DESA, y=SHANNON_AVG, fill = DESA)) +
#       geom_bar(stat="identity", color = "black") +
#       xlab("Desa") +
#       ylab("Index") +
#       #geom_text(aes(label=SHANNON_AVG), vjust=-0.3, size=3.5) +
#       theme_minimal() +
#       scale_fill_manual(values = c("green", "#0474c4"),
#                     labels = c("Lantangpeo","Tompotanah")) +
#       theme(legend.title=element_blank())

```

```{r totalMaxN}
# 
# Maxn_List <- c()
# 
# for(i in 1:ncol(URUV_data)){
#   if(grepl("MAXN", colnames(URUV_data[i]))){
#     Maxn_List <- append(Maxn_List,i)
#   }}
# 
# URUV_data$MAXN_TOTAL <- rowSums(URUV_data[ , Maxn_List], na.rm=TRUE)

ggplot(URUV_data, aes(x=DESA, y=MAXN_TOTAL)) + 
  geom_boxplot() 
  #geom_jitter(shape=16, position=position_jitter(0.1))

ggplot(URUV_data, aes(x=SITE_TYPE, y=MAXN_TOTAL)) + 
  geom_boxplot() 
  #geom_jitter(shape=16, position=position_jitter(0.1))

```

```{r habitatPreference, fig.cap = 'habitat preference'}

#TotalMaxN and Shannon's Diversity for each observation
dontInclude <- c("UNIDGUPPY", "PIPEFISH", "TOTAL")

preference_dataframe <- data.frame(SITE_TYPE = as.factor(c("D", "E", "L")))

# for(i in 1:nrow(URUV_data)){
#   species_counts <- c()
#   k <- 1
  for(j in 1:ncol(URUV_data)){
    if(grepl(paste(dontInclude, collapse = "|"), colnames(URUV_data[j])) == FALSE & grepl("MAXN", colnames(URUV_data[j]))){
      tot_obs <- sum(URUV_data[,j])
      calc_df <- data.frame(SITE_TYPE = URUV_data$SITE_TYPE,
                            SPECIES = URUV_data[,j])
      prop <- calc_df %>%
        group_by(SITE_TYPE)%>%
        summarise(!!paste0('prop_',colnames(URUV_data[j])) := (sum(SPECIES)/tot_obs))
      
      preference_dataframe <- left_join(preference_dataframe, prop, by = 'SITE_TYPE')
    }
  }

preference_dataframe$totProps <- rowSums(preference_dataframe[,2:ncol(preference_dataframe)])

ggplot(data=preference_dataframe, aes(x=SITE_TYPE, y=totProps, fill = SITE_TYPE)) +
      geom_bar(stat="identity", color = "black") +
      xlab("Jenis Mangrove") +
      ylab("Index") +
      #geom_text(aes(label=SHANNON_AVG), vjust=-0.3, size=3.5) +
      theme_minimal() +
      scale_fill_manual(values = c("#b41515", "#ffff00", "#0474c4"),
                    labels = c("Dihancur","EMR", "Alami")) +
      theme(legend.title=element_blank())
```

\newpage

# ANOVAS AND STATS
```{r ANOVA_MAXN}

# LATER maybe try a PCA https://builtin.com/data-science/step-step-explanation-principal-component-analysis

# ONE WAY ANOVA CHECKING EFFECT OF SITE AND DESA
# https://www.scribbr.com/statistics/anova-in-r/

one.way_Overall <- aov(MAXN_TOTAL ~ SITE_TYPE, data = URUV_data)
summary(one.way_Overall)

one.way_Desa <- aov(MAXN_TOTAL ~ DESA, data = URUV_data)
summary(one.way_Desa)


```

```{r ANOVA_SHANNON}

# one.way_Total <- aov(NO_FISHSPECIES ~ SITE_TYPE, data = URUV_data)
# 2 WAY ANOVA CHECKING SITE AND OVERALL MAXN

two.way_Overall <- aov(SHANNON_DIV ~ SITE_TYPE + DESA, data = URUV_data)
summary(two.way_Overall)

Interaction_Overall <- aov(SHANNON_DIV ~ SITE_TYPE * DESA, data = URUV_data)
summary(Interaction_Overall)


```

\newpage

# STATS
```{r depthplotting}

# plot(URUV_data$WATER_DEPTH_BEFORE, URUV_data$MAXN_TOTAL)
# abline(lm(MAXN_TOTAL ~ WATER_DEPTH_BEFORE, data = URUV_data))
# 
# lm(MAXN_TOTAL ~ WATER_DEPTH_BEFORE, data = URUV_data)

ggplot(data=URUV_data, aes(x=WATER_DEPTH_BEFORE, y=MAXN_TOTAL)) +
        geom_smooth(method="lm") +
        geom_point() +
        stat_regline_equation(label.x=15, label.y=50) +
        stat_cor(aes(label=..rr.label..), label.x=15, label.y=40)

```

```{r tideplotting}

# plot(URUV_data$TIDE_HEIGHT, URUV_data$MAXN_TOTAL)

ggplot(data=URUV_data, aes(x=TIDE_HEIGHT, y=MAXN_TOTAL)) +
        geom_smooth(method="lm") +
        geom_point() +
        stat_regline_equation(label.x=.1, label.y=50) +
        stat_cor(aes(label=..rr.label..), label.x=.1, label.y=40)

```

```{r vegplotting}
#plot(URUV_data$VEGITATION, URUV_data$MAXN_TOTAL)

ggplot(data=URUV_data, aes(x=VEGITATION, y=MAXN_TOTAL)) +
        geom_smooth(method="lm") +
        geom_point() +
        stat_regline_equation(label.x=15, label.y=50) +
        stat_cor(aes(label=..rr.label..), label.x=15, label.y=40)

```

```{r plottingVis}

plot(URUV_data$VISIBILITY, URUV_data$MAXN_TOTAL)

ggplot(data=URUV_data, aes(x=VISIBILITY, y=MAXN_TOTAL)) +
        geom_smooth(method="lm") +
        geom_point() +
        stat_regline_equation(label.x=15, label.y=50) +
        stat_cor(aes(label=..rr.label..), label.x=15, label.y=40)
```

\newpage
```{r MAXN_bymonth}

StackedBar <- URUV_data %>% 
   group_by(MONTH, SITE_TYPE) %>% 
   summarise(JUMLAH_IKAN = sum(MAXN_TOTAL), SHANNON_MEAN = mean(SHANNON_DIV))

ggplot(StackedBar, aes(fill=SITE_TYPE, y=JUMLAH_IKAN, x=MONTH)) + 
    geom_bar(position="stack", stat="identity", color = "black") +
    xlab("Bulan") +
    ylab("Jumlah Ikan") +
    theme_minimal() +
    scale_fill_manual(values = c("#b41515", "#ffff00", "#0474c4"),
                  labels = c("Dihancur","EMR", "Alami")) +
    theme(legend.title=element_blank())


```

```{r Shannon_bymonth}

ggplot(StackedBar, aes(fill=SITE_TYPE, y=SHANNON_MEAN, x=MONTH)) + 
    geom_bar(position="stack", stat="identity", color = "black") +
    xlab("Bulan") +
    ylab("SDI") +
    theme_minimal() +
    scale_fill_manual(values = c("#b41515", "#ffff00", "#0474c4"),
                  labels = c("Dihancur","EMR", "Alami")) +
    theme(legend.title=element_blank())


```



\newpage

# INDIVIDUAL SPECIES

```{r speciesSort}
colList <- c()

#REMOVE SPECIES IN DONT INCLUDE FROM HERE
for(i in 1:ncol(URUV_data)){
  if(grepl("MAXN", colnames(URUV_data[i])) & sum(URUV_data[i] > 0) > 20){ #Sort Through all MaxN's calculated
    colList <- append(colList, i)
    # & sum(colnames(URUV_data[i]) > 0) > 5
    #Need to fully rename column so ggplot can read it. Make separate datasheet
    Yaxistitle <- colnames(URUV_data[i])
    data1 <- URUV_data %>%
      rename("MAXN_TARGET" = colnames(URUV_data[i]))
    
    #data1$MONTH <- month(data1$DATE)
    
    #Graph boxplot per desa
    print(ggplot(data1, aes(x=DESA, y=MAXN_TARGET)) +
      geom_boxplot() +
      geom_jitter(shape=16, position=position_jitter(0.2)) +
      ylab(Yaxistitle))

    #Graph boxplot per site type
    print(ggplot(data1, aes(x=SITE_TYPE, y=MAXN_TARGET)) +
      geom_boxplot() +
      geom_jitter(shape=16, position=position_jitter(0.2)) +
      ylab(Yaxistitle))
    
    
    #Graph temporal patterns
    
    SpeciesPerMonth <- data1 %>%
      group_by(MONTH) %>%
      summarize(sum(MAXN_TARGET))
    colnames(SpeciesPerMonth) <-c("MONTH", "TOTAL")

    # SpeciesPerMonth$MONTH <- as.integer(SpeciesPerMonth$MONTH)
    # 
    # MONTHLIST <- data.frame(MONTH = c(1:12))
    # 
    # temporalSpeciesData <- left_join(MONTHLIST, SpeciesPerMonth)
    # 
    # temporalSpeciesData[is.na(temporalSpeciesData)] <- 0

    print(ggplot(SpeciesPerMonth, aes(x = MONTH, y = TOTAL)) +
      geom_bar(stat = "identity") + 
       ylab(Yaxistitle) )
    
    # Graph total number of fish in each siteType
    
    ikanTotal <- data1 %>%
      group_by(SITE_TYPE) %>%
      summarise(TOTAL_FISH = sum(MAXN_TARGET))
    
    print(ggplot(data=ikanTotal, aes(x=SITE_TYPE, y=TOTAL_FISH, fill = SITE_TYPE)) +
      geom_bar(stat="identity", color = "black") +
      xlab("Jenis Mangrove") +
      ylab(paste("Jumlah Ikan", Yaxistitle)) +
      geom_text(aes(label=TOTAL_FISH), vjust=-0.3, size=3.5) +
      theme_minimal() +
      scale_fill_manual(values = c("#b41515", "#ffff00", "#0474c4"),
                    labels = c("Dihancur","EMR", "Alami")) +
      theme(legend.title=element_blank()))
      
      
    
  }
  
  
  
}



```

\newpage

# QUALITY CHECKS

```{r vegitationcheck}

plot(x = 1,
     type = "n",
     xlim = c(0, 100), 
     ylim = c(0, 10),
     pch = 16,
     xlab = "Vegitation", 
     ylab = "Total Species")

# Add coral2 points for male data
points(x = URUV_data$VEGITATION[URUV_data$SITE_TYPE == "D"],
       y = URUV_data$NO_ALLSPECIES[URUV_data$SITE_TYPE == "D"],
       pch = 16,
       col = "coral2", trans.val = .8)

# Add steelblue points for female data
points(x = URUV_data$VEGITATION[URUV_data$SITE_TYPE == "E"],
       y = URUV_data$NO_ALLSPECIES[URUV_data$SITE_TYPE == "E"],
       pch = 16,
       col = "steelblue3", trans.val = .8)

points(x = URUV_data$VEGITATION[URUV_data$SITE_TYPE == "L"],
       y = URUV_data$NO_ALLSPECIES[URUV_data$SITE_TYPE == "L"],
       pch = 16,
       col = "chartreuse2", trans.val = .8)

```

```{r vegitationcheck2}

plot(x = 1,
     type = "n",
     xlim = c(0, 100), 
     ylim = c(0, 10),
     pch = 16,
     xlab = "Vegitation", 
     ylab = "Total Species")

# Add coral2 points for degraded data
points(x = URUV_data$VEGITATION[URUV_data$SITE_TYPE == "D"],
       y = URUV_data$NO_FISHSPECIES[URUV_data$SITE_TYPE == "D"],
       pch = 16,
       col = "coral2", trans.val = .8)

# Add steelblue points for EMR data
points(x = URUV_data$VEGITATION[URUV_data$SITE_TYPE == "E"],
       y = URUV_data$NO_FISHSPECIES[URUV_data$SITE_TYPE == "E"],
       pch = 16,
       col = "steelblue3", trans.val = .8)

#Green points for lush data
points(x = URUV_data$VEGITATION[URUV_data$SITE_TYPE == "L"],
       y = URUV_data$NO_FISHSPECIES[URUV_data$SITE_TYPE == "L"],
       pch = 16,
       col = "chartreuse2", trans.val = .8)

```

```{r batterycheck, eval = FALSE }


ggplot(URUV_data, aes(x=NO_BATTERY, y=TOTALTIME_RECORDING)) + 
  geom_bar(stat='identity')

```
