---
title: "DataAnalysis"
author: "Sophie Wulfing"
date: "2026-04-24"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, dev="cairo_pdf")

# List of each species, local name and relative abundance
# ^ Percent time found in each location
# Do the modelling stuff in claude
# Simpson diversity has a lot of results
# Maybe focus on fished species in the region?
# NMDS PLOT for a desa vs site type analysis
# Similarity percentage analysis - see which fish species are contributing to differences in desas vs mangrove types


# FIX DESA LABELS


library(plyr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(ggpubr)
library(rlang)



#Make a MasterDatasheet with all months data
# CHANGE EVERY MONTH
completedData <- c("02.2024", "03.2024", "04.2024", "05.2024", "06.2024", "07.2024", "08.2024", "09.2024")

masterData <- data.frame()

for(i in 1:length(completedData)){
  addedData <- data.frame(read.csv(paste0("URUV/RecordingData_",completedData[i],".csv")))
  
  #All NA maxN's changed to 0s
  for(k in 1:ncol(addedData)){
    if(grepl("MAXN", colnames(addedData[k]))){
      addedData[k][is.na(addedData[k])] <- 0
    }
    else if(grepl("TIME_1ST", colnames(addedData[k])) | grepl("T1_", colnames(addedData[k]))){
      addedData[k][is.na(addedData[k])] <- NA
      # Converting all Time 1st columns to total seconds
      for(j in 1:nrow(addedData))
        addedData[j,k] <- as.numeric(hms(addedData[j,k]))
    }
    }
  
  masterData <- rbind.fill(masterData, addedData)
}

masterData <- masterData %>%
  filter( F1_TIME != "") %>%
  filter(!is.na(F1_TIME))
# 
# # DELETE THIS AFTER PRESENTATION!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# masterData <- masterData %>%
#   filter(MONTH != "JUNE")

#Need to chage NAs again
for(j in 1:ncol(masterData)){
    if(grepl("MAXN", colnames(masterData[j]))){
      masterData[j][is.na(masterData[j])] <- 0
    }}

#View(masterData)
write.csv(masterData, "C:/Users/swulfing/Documents/GitHub/TanakekeProject/URUVS/Datasheets/Master_RecordingData.csv")

URUV_data <- masterData

```

```{r fxnCombineSpecies}


combineSpecies <- function(NAME1, NAME2, NEWNAME) {
# NAME1 <- "SHRIMP"
# NAME2 <- "GUPPYB"
# NEWNAME <- "SHRIMP"


  SPECIES_Compare <- URUV_data %>%
    select(ends_with(NAME1) | ends_with(NAME2))
  
  # Remove these columns from original dataset
  NEW_URUV <- URUV_data[,!names(URUV_data) %in% colnames(SPECIES_Compare)]
  
  # CALCULATE NEW MAXN  
  MAXN_cols <- grep("MAXN", names(SPECIES_Compare), value = TRUE)
  MAXN_Compare <- data.frame(x = c(NA))
  colnames(MAXN_Compare) <- paste0("MAXN_", NEWNAME)
  for(i in 1:nrow(SPECIES_Compare)){
    d1 <- as.numeric(SPECIES_Compare[i,MAXN_cols[1]])
    d2 <- as.numeric(SPECIES_Compare[i,MAXN_cols[2]])
    
    MAXN_Compare[i,1] <- pmax(d1, d2, na.rm = TRUE)
  }
  #colnames(MAXN_Compare) <- paste0("MAXN_", NEWNAME)
  
  # CALCULATE NEW TIME_1ST 
  TIME_1ST_cols <- grep("TIME_1ST", names(SPECIES_Compare), value = TRUE)
  TIME_1ST_Compare <- data.frame(x = c(NA))
  colnames(TIME_1ST_Compare) <- paste0("TIME_1ST_", NEWNAME)
  for(i in 1:nrow(SPECIES_Compare)){
    d1 <- as.numeric(SPECIES_Compare[i,TIME_1ST_cols[1]])
    d2 <- as.numeric(SPECIES_Compare[i,TIME_1ST_cols[2]])
    
    TIME_1ST_Compare[i,1] <- pmax(d1, d2, na.rm = TRUE)
  }
  
   # CALCULATE NEW T1  
  T1_cols <- grep("T1", names(SPECIES_Compare), value = TRUE)
  T1_Compare <- data.frame(x = c(NA))
  colnames(T1_Compare) <- paste0("T1_", NEWNAME)
  for(i in 1:nrow(SPECIES_Compare)){
    d1 <- as.numeric(SPECIES_Compare[i,T1_cols[1]])
    d2 <- as.numeric(SPECIES_Compare[i,T1_cols[2]])
    
    T1_Compare[i,1] <- pmax(d1, d2, na.rm = TRUE)
  }
#   
# #FIX THIS IT STILL DOESN'T WORK
#   # # CALCULATE NEW TIME_1ST
#   TIME_1ST_cols <- grep("TIME_1ST", names(SPECIES_Compare), value = TRUE)
#   TIME_1ST_Compare <- pmin(SPECIES_Compare[TIME_1ST_cols[1]], SPECIES_Compare[TIME_1ST_cols[2]], na.rm = TRUE)
#   colnames(TIME_1ST_Compare) <- paste0("TIME_1ST", NEWNAME)
# 
#   # CALCULATE NEW T1_
#   T1_cols <- grep("T1_", names(SPECIES_Compare), value = TRUE)
#   T1_Compare <- pmin(SPECIES_Compare[T1_cols[1]], SPECIES_Compare[T1_cols[2]], na.rm = TRUE)
#   colnames(T1_Compare) <- paste0("T1_", NEWNAME)
  
  #APPEND TO DATASET AND REPLACE
  NEW_URUV <- cbind(NEW_URUV, MAXN_Compare, TIME_1ST_Compare, T1_Compare)
  
  URUV_data <<- NEW_URUV
  
}


```

```{r testing, eval = FALSE}

# species <- masterData %>%
#   select(contains('MAXN'))
# 
# speciesGuide <- data.frame(
#   dataCode = unlist(lapply(colnames(species), function(x) gsub("MAXN_", "", x))),
#   colName = colnames(species)
# )
# 
# write.csv(speciesGuide, 'URUV/speciesGuide1.csv')

```

```{r dataClean}
library(chron)
URUV_data <- masterData

URUV_data$DATE <- as.Date(URUV_data$DATE, format = "%d/%m/%Y")

URUV_data <- URUV_data %>% #Take out unused videos
  dplyr::rename(MAXN_UNIDJUVENILE = MAXN_GUPPYA,
         T1_UNIDJUVENILE = T1_GUPPYA,
         TIME_1STUNIDJUVENILE = TIME_1STGUPPYA) %>%
  rowwise() %>%
  mutate(WATER_DEPTH_AVERAGE = mean(c(WATER_DEPTH_BEFORE, WATER_DEPTH_AFTER), na.rm=TRUE)) #Take avg depth during recording
  

# Making months factors
URUV_data$MONTH <- factor(URUV_data$MONTH, levels = c("JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"))
URUV_data$SITE_TYPE <- factor(URUV_data$SITE_TYPE, levels = c("D", "E", "L"))
URUV_data$DESA <- factor(URUV_data$DESA)

# CHANGE ALL RENAMES

# COMBINE SPECIES

combineSpecies("SHRIMP", "GUPPYB", "SHRIMP")
combineSpecies('FISHM','FISHG','FISHM')
combineSpecies('FISHF','GUPPYC','FISHF')
combineSpecies('FISHK','FISHL','FISHK')
combineSpecies('FISHO','CHEETAGIRLZ','FISHO')
combineSpecies('BIGBOI','VERTFISH','BIGBOI')
combineSpecies('FISHA','YELLOWGUPPY','FISHA')
combineSpecies('FISHQ','FISHP','FISHQ')
combineSpecies('SANDFISH','LILFREAK','SANDFISH')
combineSpecies('FISHF','FISHR','FISHF')
combineSpecies('FISHQ','FISHS','FISHQ')
combineSpecies('FISHE','EYELINER','FISHE')
combineSpecies('FISHO','FISHBT','FISHO')


#Change all time columns to be read as times and h/m/s to be read in as total seconds (my workaround for dealing with time vs timer datasets)
for(i in 1:ncol(URUV_data)){
  if(colnames(URUV_data[i]) %in% c("TIME_DROPPED", "TIME_PICKEDUP")){
    #URUV_data[[i]] <- strptime(URUV_data[[i]], format = "%H:%M")
    URUV_data[[i]] <- times(paste0(URUV_data[[i]], ":00"))
    
    
  }else if(colnames(URUV_data[i]) != "NOTES_TIME" & (colnames(URUV_data[i]) %in% c("TOTALTIME_RECORDING", "ANALYSISTIME_START", "ANALYSISTIME_END", "TOTALTIME_ANALYSIS"))){
    for(j in 1:nrow(URUV_data[i]))
    URUV_data[j,i] <- as.numeric(hms(URUV_data[j,i]))
    
    
  }else if(colnames(URUV_data[i]) == "TIME_TOTALFOOTAGE"){
    URUV_data[[i]] <- paste0(URUV_data[[i]], ":00")
    for(j in 1:nrow(URUV_data[i]))
    URUV_data[j,i] <- as.numeric(hms(URUV_data[j,i]))
  }
}

#TotalMaxN and Shannon's Diversity for each observation
dontInclude <- c("MAXN_UNIDGUPPY", "MAXN_PIPEFISH", "MAXN_TOTAL", 'MAXN_UNIDJUVENILE') ## UPDATE THIS SO WE KNOW WHAT NOT TO INCLUDE

for(i in 1:nrow(URUV_data)){
  species_counts <- c()
  k <- 1
  for(j in 1:ncol(URUV_data)){
    if(!(colnames(URUV_data[j]) %in% dontInclude) & grepl("MAXN", colnames(URUV_data[j])) & URUV_data[i,j] > 0){
      species_counts[k] <- as.numeric(URUV_data[i,j])
      k <- k+1
    }
  }
  
  species_proportions <- species_counts / sum(species_counts)
  shannon_diversity <- -sum(species_proportions * log(species_proportions))
  
  maxn_tot <- sum(species_counts)
  simpson_NUM <- species_counts * (species_counts - 1)
  simpson_DEN <- maxn_tot * (maxn_tot - 1)
  simpson_diversity <- sum(simpson_NUM)/simpson_DEN
  
  
  URUV_data$SHANNON_DIV[i] <- shannon_diversity
  URUV_data$SIMPSON_DIV[i] <- simpson_diversity
  URUV_data$MAXN_TOTAL[i] <- maxn_tot
  
}

for(i in 1:nrow(URUV_data)){
  if(URUV_data$MAXN_TOTAL[i] == 1){URUV_data$SIMPSON_DIV[i] <- 0}
}

checkData <- URUV_data %>%
  select(MONTH, DATE, SITENAME_COMBINE, NO_ALLSPECIES, SIMPSON_DIV, SHANNON_DIV, MAXN_TOTAL, NO_FISHSPECIES, contains("MAXN"))

write.csv(URUV_data, "MasterRecordingData_clean.csv")
```

```{r AllSpecies, results = 'asis', echo = FALSE, fig.show = "hold", out.width = "50%", fig.cap = 'Total number of species in each category'}

ggplot(URUV_data, aes(x=DESA, y=NO_ALLSPECIES)) + 
  geom_boxplot() 
  #geom_jitter(shape=16, position=position_jitter(0.2))

ggplot(URUV_data, aes(x=SITE_TYPE, y=NO_ALLSPECIES)) + 
  geom_boxplot() 
  #geom_jitter(shape=16, position=position_jitter(0.2))

```

```{r FishSpecies, results = 'asis', echo = FALSE, fig.show = "hold", out.width = "50%"}

ggplot(URUV_data, aes(x=DESA, y=NO_FISHSPECIES)) + 
  geom_boxplot() 
  #geom_jitter(shape=16, position=position_jitter(0.1))

ggplot(URUV_data, aes(x=SITE_TYPE, y=NO_FISHSPECIES)) + 
  geom_boxplot() 
  #geom_jitter(shape=16, position=position_jitter(0.1))

```

```{r ShannonsDiversity}
library(dplyr)
# MAKE LIST OF SPECIES NOT TO INCLUDE UNIDGUPPY, 

# DOUBLE CHECK THIS CALCULATION. based off this https://sqlpad.io/tutorial/shannon-diversity-calculate/

# # Sample data: species counts
# species_counts <- c(10, 20, 30, 40)
# 
# # Calculate proportions
# species_proportions <- species_counts / sum(species_counts)
# 
# # Calculate Shannon Diversity Index
# shannon_diversity <- -sum(species_proportions * log(species_proportions))
# print(shannon_diversity)


diversity <- URUV_data %>%
      dplyr::group_by(SITE_TYPE) %>%
      dplyr::summarise(SHANNON_AVG = mean(SHANNON_DIV, na.rm = TRUE),
                SHANNON_SD = sd(SHANNON_DIV, na.rm = TRUE),
                SIMPSON_AVG = mean(SIMPSON_DIV, na.rm = TRUE),
                SIMPSON_SD = sd(SIMPSON_DIV, na.rm = TRUE)
                )

desa <- URUV_data %>%
      dplyr::group_by(DESA) %>%
      dplyr::summarise(SHANNON_AVG = mean(SHANNON_DIV, na.rm = TRUE),
                SHANNON_SD = sd(SHANNON_DIV, na.rm = TRUE),
                SIMPSON_AVG = mean(SIMPSON_DIV, na.rm = TRUE),
                SIMPSON_SD = sd(SIMPSON_DIV, na.rm = TRUE)
                )

ggplot(data=diversity, aes(x=SITE_TYPE, y=SHANNON_AVG, fill = SITE_TYPE)) +
      geom_bar(stat="identity", color = "black") +
      geom_errorbar( aes(x=SITE_TYPE, ymin=SHANNON_AVG-SHANNON_SD, ymax=SHANNON_AVG+SHANNON_SD), width=0.4, alpha=0.9, size=1.3) +
      xlab("Jenis Mangrove") +
      ylab("Shannon Index") +
      #geom_text(aes(label=SHANNON_AVG), vjust=-0.3, size=3.5) +
      theme_minimal() +
      scale_fill_manual(values = c("#b41515", "#ffff00", "#0474c4"),
                    labels = c("Dihancur","EMR", "Alami")) +
      theme(legend.title=element_blank())

ggplot(data=desa, aes(x=DESA, y=SHANNON_AVG, fill = DESA)) +
      geom_bar(stat="identity", color = "black") +
      geom_errorbar( aes(x=DESA, ymin=SHANNON_AVG-SHANNON_SD, ymax=SHANNON_AVG+SHANNON_SD), width=0.4, alpha=0.9, size=1.3) +
      xlab("Jenis Mangrove") +
      ylab("Shannon Index") +
      #geom_text(aes(label=SHANNON_AVG), vjust=-0.3, size=3.5) +
      theme_minimal() +
      scale_fill_manual(values = c("#b41515", "#ffff00", "#0474c4"),
                    labels = c("Dihancur","EMR", "Alami")) +
      theme(legend.title=element_blank())

# ggplot(data=desa, aes(x=DESA, y=SHANNON_AVG, fill = DESA)) +
#       geom_bar(stat="identity", color = "black") +
#       xlab("Desa") +
#       ylab("Index") +
#       #geom_text(aes(label=SHANNON_AVG), vjust=-0.3, size=3.5) +
#       theme_minimal() +
#       scale_fill_manual(values = c("green", "#0474c4"),
#                     labels = c("Lantangpeo","Tompotanah")) +
#       theme(legend.title=element_blank())

```

```{r Simpson}
ggplot(data=diversity, aes(x=SITE_TYPE, y=SIMPSON_AVG, fill = SITE_TYPE)) +
      geom_bar(stat="identity", color = "black") +
      geom_errorbar( aes(x=SITE_TYPE, ymin=SIMPSON_AVG-SIMPSON_SD, ymax=SIMPSON_AVG+SIMPSON_SD), width=0.4, alpha=0.9, size=1.3) +
      xlab("Jenis Mangrove") +
      ylab("Simpson Index") +
      #geom_text(aes(label=SIMPSON_AVG), vjust=-0.3, size=3.5) +
      theme_minimal() +
      scale_fill_manual(values = c("#b41515", "#ffff00", "#0474c4"),
                    labels = c("Dihancur","EMR", "Alami")) +
      theme(legend.title=element_blank())

ggplot(data=desa, aes(x=DESA, y=SIMPSON_AVG, fill = DESA)) +
      geom_bar(stat="identity", color = "black") +
      geom_errorbar( aes(x=DESA, ymin=SIMPSON_AVG-SIMPSON_SD, ymax=SIMPSON_AVG+SIMPSON_SD), width=0.4, alpha=0.9, size=1.3) +
      xlab("Jenis Mangrove") +
      ylab("Simpson Index") +
      #geom_text(aes(label=SIMPSON_AVG), vjust=-0.3, size=3.5) +
      theme_minimal() +
      scale_fill_manual(values = c("#b41515", "#ffff00", "#0474c4"),
                    labels = c("Dihancur","EMR", "Alami")) +
      theme(legend.title=element_blank())

```

```{r totalMaxN}
# 
# Maxn_List <- c()
# 
# for(i in 1:ncol(URUV_data)){
#   if(grepl("MAXN", colnames(URUV_data[i]))){
#     Maxn_List <- append(Maxn_List,i)
#   }}
# 
# URUV_data$MAXN_TOTAL <- rowSums(URUV_data[ , Maxn_List], na.rm=TRUE)

ggplot(URUV_data, aes(x=DESA, y=MAXN_TOTAL)) + 
  geom_boxplot() 
  #geom_jitter(shape=16, position=position_jitter(0.1))

ggplot(URUV_data, aes(x=SITE_TYPE, y=MAXN_TOTAL)) + 
  geom_boxplot() 
  #geom_jitter(shape=16, position=position_jitter(0.1))

```

```{r habitatPreference, fig.cap = 'habitat preference. This calculates the proportion of each species that were found in each site type'}

#TotalMaxN and Shannon's Diversity for each observation
dontInclude <- c("UNIDGUPPY", "PIPEFISH", "TOTAL")

preference_dataframe <- data.frame(SITE_TYPE = as.factor(c("D", "E", "L")))

# for(i in 1:nrow(URUV_data)){
#   species_counts <- c()
#   k <- 1
  for(j in 1:ncol(URUV_data)){
    if(grepl(paste(dontInclude, collapse = "|"), colnames(URUV_data[j])) == FALSE & grepl("MAXN", colnames(URUV_data[j]))){
      tot_obs <- sum(URUV_data[,j])
      calc_df <- data.frame(SITE_TYPE = URUV_data$SITE_TYPE,
                            SPECIES = URUV_data[,j])
      prop <- calc_df %>%
        group_by(SITE_TYPE)%>%
        dplyr::summarise(!!paste0('prop_',colnames(URUV_data[j])) := (sum(SPECIES)/tot_obs))
      
      preference_dataframe <- left_join(preference_dataframe, prop, by = 'SITE_TYPE')
    }
  }

preference_dataframe$totProps <- rowSums(preference_dataframe[,2:ncol(preference_dataframe)])

ggplot(data=preference_dataframe, aes(x=SITE_TYPE, y=totProps, fill = SITE_TYPE)) +
      geom_bar(stat="identity", color = "black") +
      xlab("Jenis Mangrove") +
      ylab("Index") +
      #geom_text(aes(label=SHANNON_AVG), vjust=-0.3, size=3.5) +
      theme_minimal() +
      scale_fill_manual(values = c("#b41515", "#ffff00", "#0474c4"),
                    labels = c("Dihancur","EMR", "Alami")) +
      theme(legend.title=element_blank())
```

\newpage

# ANOVAS

There seems to be somewhat of a realtionship in between site type and total max n and site type and simpson's diversity, just not with shannon diversity

```{r ANOVA_MAXN}

# LATER maybe try a PCA https://builtin.com/data-science/step-step-explanation-principal-component-analysis

# ONE WAY ANOVA CHECKING EFFECT OF SITE AND DESA
# https://www.scribbr.com/statistics/anova-in-r/

one.way_Overall <- aov(MAXN_TOTAL ~ SITE_TYPE, data = URUV_data)
summary(one.way_Overall)

one.way_Desa <- aov(MAXN_TOTAL ~ DESA, data = URUV_data)
summary(one.way_Desa)


```

```{r ANOVA_SHANNON}

# one.way_Total <- aov(NO_FISHSPECIES ~ SITE_TYPE, data = URUV_data)
# 2 WAY ANOVA CHECKING SITE AND OVERALL MAXN

two.way_Overall <- aov(SHANNON_DIV ~ SITE_TYPE + DESA, data = URUV_data)
summary(two.way_Overall)

Interaction_Overall <- aov(SHANNON_DIV ~ SITE_TYPE * DESA, data = URUV_data)
summary(Interaction_Overall)


```

```{r ANOVA_SIMPSON}

# one.way_Total <- aov(NO_FISHSPECIES ~ SITE_TYPE, data = URUV_data)
# 2 WAY ANOVA CHECKING SITE AND OVERALL MAXN

two.way_Overall <- aov(SIMPSON_DIV ~ SITE_TYPE + DESA, data = URUV_data)
summary(two.way_Overall)

Interaction_Overall <- aov(SIMPSON_DIV ~ SITE_TYPE * DESA, data = URUV_data)
summary(Interaction_Overall)


```

```{r MAXN_bymonth}

StackedBar <- URUV_data %>% 
   dplyr::group_by(MONTH, SITE_TYPE) %>% 
   dplyr::summarise(JUMLAH_IKAN = sum(MAXN_TOTAL), 
             SHANNON_MEAN = mean(SHANNON_DIV, na.rm = TRUE),
             SIMPSON_MEAN = mean(SIMPSON_DIV, na.rm = TRUE))

ggplot(StackedBar, aes(fill=SITE_TYPE, y=JUMLAH_IKAN, x=MONTH)) + 
    geom_bar(position="stack", stat="identity", color = "black") +
    xlab("Bulan") +
    ylab("Jumlah Ikan/ total fish") +
    theme_minimal() +
    scale_fill_manual(values = c("#b41515", "#ffff00", "#0474c4"),
                  labels = c("Dihancur","EMR", "Alami")) +
    theme(legend.title=element_blank())


```

```{r Shannon_bymonth}

ggplot(StackedBar, aes(fill=SITE_TYPE, y=SHANNON_MEAN, x=MONTH)) + 
    geom_bar(position="stack", stat="identity", color = "black") +
    xlab("Bulan") +
    ylab("Shannon index") +
    theme_minimal() +
    scale_fill_manual(values = c("#b41515", "#ffff00", "#0474c4"),
                  labels = c("Dihancur","EMR", "Alami")) +
    theme(legend.title=element_blank())


```

```{r Simpson_bymonth}

ggplot(StackedBar, aes(fill=SITE_TYPE, y=SIMPSON_MEAN, x=MONTH)) + 
    geom_bar(position="stack", stat="identity", color = "black") +
    xlab("Bulan") +
    ylab("Simpson index") +
    theme_minimal() +
    scale_fill_manual(values = c("#b41515", "#ffff00", "#0474c4"),
                  labels = c("Dihancur","EMR", "Alami")) +
    theme(legend.title=element_blank())


```
