---
title: "HOBO_Analysis"
author: "Sophie Wulfing"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(cowplot)
library(ggplot2)
setwd("C:/Users/Sophi/Documents/GitHub/TanakekeProject/URUVS/Datasheets")

```

```{r readData}

# From here: https://rpubs.com/cgb-grupstra/moorea-hobo-20190314
# STILL NEED TO FILTURE OUT THE TIME BEFORE INSTALLATION

# #Later make a loop that goes through each month and combines each month of the same logger. 
# #I THINK it will look something like this:
# 
# monthlogs <- c("02", "03")
# Loggernames <- c("D6", "L4", "E5")
# 
# set blank df for each loggername
# 
# foorloop Loggernames()
# forloopmonth logs(read in dataset with monthlog and loggername in it, rename column headers and clean *as below*, then stack all datasets of one logger on top of eachother and save that as a df)

# Read in logger info

D6_HOBO <- read.csv("HOBO/HOBO02.2024_21370988_3_D6.csv")
L4_HOBO <- read.csv("HOBO/HOBO02.2024_21370989_2_L4.csv")
E5_HOBO <- read.csv("HOBO/HOBO02.2024_21513093_1_E5.csv")

colnames(D6_HOBO) <- c("unique", "date", "temp", "light")
#D6_HOBO$date <- as.Date(D6_HOBO$date, format = "%m/%d/%Y HH:MM:SS")

colnames(L4_HOBO) <- c("unique", "date", "temp", "light")
#L4_HOBO$date <- as.Date(L4_HOBO$date, format = "%m/%d/%Y HH:MM:SS")

colnames(E5_HOBO) <- c("unique", "date", "temp", "light")
#E5_HOBO$date <- as.Date(L4_HOBO$date, format = "%m/%d/%Y HH:MM:SS")
  
ggplot() +
  geom_point(data=D6_HOBO,aes(x=date,
    y=temp), size = 1, alpha = 1/10, color = "red") +
  geom_point(data=L4_HOBO,aes(x=date,
    y=temp), size = 1, alpha = 1/10, color = "green") +
  geom_point(data=E5_HOBO,aes(x=date,
    y=temp), size = 1, alpha = 1/10, color = "blue")

ggplot() +
  geom_point(data=D6_HOBO,aes(x=date,
    y=light), size = 1, alpha = 1/10, color = "red") +
  geom_point(data=L4_HOBO,aes(x=date,
    y=light), size = 1, alpha = 1/10, color = "green") +
  geom_point(data=E5_HOBO,aes(x=date,
    y=light), size = 1, alpha = 1/10, color = "blue")
  
```

```{r dailytempaverage}

D6_avg <- tidyr::separate(D6_HOBO, 'date',
                                    into = c('longdate', 'time'),
                                    sep= ' ') %>%
  tidyr::separate('longdate',
                  into = c('month', 'day', 'year'),
                  sep= '/',
                  remove = FALSE) %>% 
  select(-matches('^$')) %>%
  group_by(year, month, day, longdate) %>%
  summarise(meantemp = mean(temp),
            meanlight = mean(light))

D6_avg$month <- factor(D6_avg$month, levels=c("02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "01"))

L4_avg <- tidyr::separate(L4_HOBO, 'date',
                                    into = c('longdate', 'time'),
                                    sep= ' ') %>%
  tidyr::separate('longdate',
                  into = c('month', 'day', 'year'),
                  sep= '/',
                  remove = FALSE) %>% 
  select(-matches('^$')) %>%
  group_by(year, month, day, longdate) %>%
  summarise(meantemp = mean(temp),
            meanlight = mean(light))

L4_avg$month <- factor(L4_avg$month, levels=c("02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "01"))

E5_avg <- tidyr::separate(E5_HOBO, 'date',
                                    into = c('longdate', 'time'),
                                    sep= ' ') %>%
  tidyr::separate('longdate',
                  into = c('month', 'day', 'year'),
                  sep= '/',
                  remove = FALSE) %>% 
  select(-matches('^$')) %>%
  group_by(year, month, day, longdate) %>%
  summarise(meantemp = mean(temp),
            meanlight = mean(light))

E5_avg$month <- factor(E5_avg$month, levels=c("2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "1"))

ggplot() +
  geom_smooth(data = D6_avg, aes(x=as.Date(longdate, format= "%m / %d / %Y"), y=meantemp), colour="red") +
  geom_smooth(data = L4_avg, aes(x=as.Date(longdate, format= "%m / %d / %Y"), y=meantemp), colour="green") +
  geom_smooth(data = E5_avg, aes(x=as.Date(longdate, format= "%m / %d / %Y"), y=meantemp), colour="blue") +
    theme_bw()+
    labs(title= "Daily temperature means", y="Daily mean temperature (°C) with 95% CI", x="Date")

ggplot() +
  geom_smooth(data = D6_avg, aes(x=as.Date(longdate, format= "%m / %d / %Y"), y=meanlight), colour="red") +
  geom_smooth(data = L4_avg, aes(x=as.Date(longdate, format= "%m / %d / %Y"), y=meanlight), colour="green") +
  geom_smooth(data = E5_avg, aes(x=as.Date(longdate, format= "%m / %d / %Y"), y=meanlight), colour="blue") +
    theme_bw()+
    labs(title= "Daily temperature means", y="Daily mean light (°C) with 95% CI", x="Date")


```