---
title: "Bibliometric Analysis of Mangroves in Fisheries"
author: "Sophie Wulfing"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE, message = FALSE)

library(bibliometrix) #load the package
library(pander) #other required packages
library(knitr)
library(kableExtra)
library(ggplot2)
library(bibliometrixData)
library(dplyr)
library(biblionetwork)
# use scopuscollection data from the package 

mangroveData <- read.csv('mangroveANDfisheriesANDbiomassORbiodiversity.csv')
rhiz_bb <- read.csv('rhizophoraANDbiomassORbiodiversity.csv')
rhiz_f <- read.csv('rhizophoraANDfisheries.csv')
rhiz_all <- read.csv('rhizophoraANDfisheriesANDbiomassORbiodiversity.csv')

```

```{r packageDownload}

package_list <- c(
  "here", # use for paths creation
  "tidyverse",
  "bib2df", # for cleaning .bib data
  "janitor", # useful functions for cleaning imported data
  "rscopus", # using Scopus API
  "biblionetwork", # creating edges
  "tidygraph", # for creating networks
  "ggraph" # plotting networks
)
for (p in package_list) {
  if (p %in% installed.packages() == FALSE) {
    install.packages(p, dependencies = TRUE)
  }
  library(p, character.only = TRUE)
}

github_list <- c(
  "agoutsmedt/networkflow", # manipulating network
  "ParkerICI/vite" # needed for the spatialisation of the network
)
for (p in github_list) {
  if (gsub(".*/", "", p) %in% installed.packages() == FALSE) {
    devtools::install_github(p)
  }
  library(gsub(".*/", "", p), character.only = TRUE)
}


```

